version: "2.2"
services:
  blazegraph:
    environment:
      - JAVA_OPTS=-Xmx700m

  metaphactory:
    #ports:
    # - "10214:8080"
    environment:
       - JAVA_OPTS=-Xmx700m
    volumes:
      - ../metaphactory-blazegraph/graphscope-service-template/app-graphscope.zip:/apps/app-graphscope.zip

#### GRAPHSCOPE ####
  graphscope:
    container_name: "${COMPOSE_PROJECT_NAME}-graphscope"
    image: "${GRAPHSCOPE}"
    restart: unless-stopped
    environment:
      JAVA_OPTS: ""
      XMX: "-Xmx1G"
      GS_CONFIGFILE: "config.yml"
    volumes:
      - ../metaphactory-blazegraph/graphscope-service-template/gs-config/gs-default/config:/opt/config
      - ../metaphactory-blazegraph/graphscope-service-template/gs-config/gs-default/logs:/opt/logs
      - ../metaphactory-blazegraph/graphscope-service-template/gs-config/gs-default/repository:/opt/repository
    networks:
      - metaphactory_network
    depends_on:
      - metaphactory
      - blazegraph
