version: "2"
services:
  stardog:
    #stardog-overwrites here
    volumes:
     - ../metaphactory-stardog/stardog-config/stardog-license-key.bin:/var/opt/stardog/stardog-license-key.bin
     - ../metaphactory-stardog/stardog-config/stardog.properties:/var/opt/stardog/stardog.properties
     - ../metaphactory-stardog/stardog-config/database-template.properties:/var/opt/stardog/database-template.properties
     # Consider to persist database file on the host machine via mounted volumes
     # Set path to your local copy of the service template folder (i.e. replace "my-deployment" in the path below)
     #  - ../metaphactory-stardog/my-deployment/stardog:/var/opt/stardog                  # main Stardog directory where database files will be stored, ideally on SSD
     #  - ../metaphactory-stardog/my-deployment/tmp:/var/opt/tmp                          # directory for temporary files (potentially big)
     #  - ../metaphactory-stardog/my-deployment/stardog-ext:/var/opt/stardog-ext          # directory for additional jar files, e.g. jdbc drivers etc
     #  - ../metaphactory-stardog/my-deployment/stardog-opennlp:/var/opt/stardog-opennlp  # directory for opennlp models

     # Optionally, for RDF files to be imported and virtual graph configs
     #- "/local/host/rdf-datasets:/datasets"
     #- "/local/host/virtual-graphs-config:/var/opt/virtual-graphs-config"
    #ports:
    # - "5820:5820" # expose on local host port 5820 i.e. for local development
    #environment:
    #  - STARDOG_SERVER_JAVA_ARGS=-Djava.io.tmpdir=/var/opt/tmp -Xms2g -Xmx2g -XX:MaxDirectMemorySize=4g

  metaphactory:
    #metaphactory-overwites here
    #ports:
    #  - "10214:8080" # expose on local host port 10214 i.e. for local development
    volumes:
     - ../metaphactory-stardog/repository-config/myDB.ttl:/runtime-data/config/repositories/default.ttl:rw
     - ../metaphactory-stardog/graphscope-service-template/app-graphscope.zip:/apps/app-graphscope.zip
    #environment:
    #  - JAVA_OPTS=-Xmx1g

 #### GRAPHSCOPE ####
  graphscope:
    container_name: "${COMPOSE_PROJECT_NAME}-graphscope"
    image: "${GRAPHSCOPE}"
    restart: unless-stopped
    environment:
      JAVA_OPTS: ""
      XMX: "-Xmx1G"
      GS_CONFIGFILE: "config.yml"
    volumes:
      # Note by default config is set to use the SPARQL endpoint at http://stardog:5820/myDB/query
      - ../metaphactory-stardog/graphscope-service-template/gs-config/gs-default-stardog/config:/opt/config
      - ../metaphactory-stardog/graphscope-service-template/gs-config/gs-default-stardog/logs:/opt/logs
      - ../metaphactory-stardog/graphscope-service-template/gs-config/gs-default-stardog/repository:/opt/repository
    networks:
      - metaphactory_network
    depends_on:
      - metaphactory
      - stardog
