version: "2.2"
services:
 blazegraph-data:
  container_name: "${COMPOSE_PROJECT_NAME}-blazegraph-data"
  image: "alpine:3.4"
  volumes:
     - /blazegraph-data

 blazegraph:
  container_name: "${COMPOSE_PROJECT_NAME}-blazegraph"
  image: "${BLAZEGRAPH_IMAGE}"
  volumes_from:
     - blazegraph-data
  environment:
     - JAVA_OPTS=-Xmx1g
  networks:
     - metaphactory_network
  # you may want to expose the port to the host 
  # i.e. if you are not using a proxy or if you want to access blazegraph admin interface from localhost 
  # ports:
  #      - "13334:8080"
  depends_on:
      - blazegraph-data
  logging:
   driver: json-file
   options:
    max-size: "200k"
    max-file: "10"

 metaphactory-data:
  container_name: "${COMPOSE_PROJECT_NAME}-metaphactory-data"
  image: "${METAPHACTORY_DATA_IMAGE}"

 metaphactory:
  container_name: "${COMPOSE_PROJECT_NAME}-metaphactory"
  image: "${METAPHACTORY_IMAGE}"
  environment:
     - PLATFORM_OPTS=-Dconfig.environment.sparqlEndpoint=http://${COMPOSE_PROJECT_NAME}-blazegraph:8080/blazegraph/sparql -Dlog4j.configurationFile=file:///var/lib/jetty/webapps/etc/log4j2-trace2.xml ${METAPHACTORY_OPTS}
     - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.${HOST_NAME}
     - JAVA_OPTS=-Xmx1g
  volumes_from:
     - metaphactory-data
  networks:
     - default
     - metaphactory_network
  # you may want to expose the port to the host
  # i.e. if you are not using a proxy
  #  ports:
  #      - "10214:8080"
  depends_on:
       - metaphactory-data
       - blazegraph
  logging:
   driver: json-file
   options:
    max-size: "200k"
    max-file: "10"

networks:
  default:
    external:
      name: nginx_proxy_network
  metaphactory_network:
